const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const C=require('../assets/publications-core.js');const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../veterinary/Vet-publications.json'),'utf8'));const audit=JSON.parse(fs.readFileSync(path.join(__dirname,'../veterinary/metadata-audit.json'),'utf8'));
test('original 236-record bibliography retained with unique IDs',()=>{assert.equal(data.length,236);assert.equal(new Set(data.map(p=>p.id)).size,236);assert.equal(C.validate(data),data);});
test('institution list is alphabetical, counted and ends in Other',()=>{const o=C.institutionOptions(data);assert.equal(o[0].value,'');assert.equal(o.at(-1).value,C.OTHER);assert.equal(o.at(-1).count,17);assert.equal(o.length-2,154);assert.deepEqual(o.slice(1,-1).map(x=>x.label),o.slice(1,-1).map(x=>x.label).sort((a,b)=>a.localeCompare(b,'en')));for(const x of o.slice(1,-1))assert.equal(C.filter(data,{institution:x.value}).length,x.count);});
test('all institutions have explicit indexed affiliation evidence',()=>{const aliases=JSON.parse(fs.readFileSync(path.join(__dirname,'../scripts/institution_aliases.json'),'utf8'));const norm=s=>C.normalize(s).replace(/[^a-z0-9]+/g,' ').trim();for(const p of data)for(const name of p.institutions){assert.equal(p.metadata_status,'matched');assert.ok(C.safeURL(p.affiliation_source_url||p.metadata_url));assert.ok(p.affiliations.some(a=>aliases[name].some(t=>(' '+norm(a)+' ').includes(' '+norm(t)+' '))),p.id+' '+name);}});
test('Other returns exactly the records without assigned institutions',()=>{assert.deepEqual(C.filter(data,{institution:C.OTHER}),data.filter(p=>!p.institutions.length));});
test('multi-institution papers can be found under every listed institution',()=>{const p=data.find(p=>p.institutions.length>2);assert.ok(p);for(const i of p.institutions)assert.ok(C.filter(data,{institution:i}).some(x=>x.id===p.id));});
test('species filters return real labelled records',()=>{for(const s of ['Canine','Feline','Equine','Porcine','Rodent','Human']){const r=C.filter(data,{species:s});assert.ok(r.length>0,s);assert.ok(r.every(p=>p.species_tags.includes(s)));}});
test('keyword search includes institutions and is accent-insensitive',()=>{assert.ok(C.filter(data,{q:'Groningen'}).length>0);assert.ok(C.filter(data,{q:'dube'}).length>0);assert.equal(C.filter(data,{q:'no-such-title-xxxxxxxx'}).length,0);});
test('year and author filters combine correctly',()=>{const r=C.filter(data,{author:'Abutarboush',year:'2013'});assert.equal(r.length,1);assert.equal(r[0].id,'bhoc-001');assert.ok(C.filter(data,{year:'1939'}).length>0);});
test('normalized journal and scope filters retain every source record',()=>{const journals=C.journalOptions(data);assert.equal(journals.reduce((sum,j)=>sum+j.count,0),236);assert.deepEqual(journals.filter(j=>j.value!==C.OTHER).map(j=>j.label),journals.filter(j=>j.value!==C.OTHER).map(j=>j.label).sort((a,b)=>a.localeCompare(b,'en')));const core=C.filter(data,{scope:'core'}),background=C.filter(data,{scope:'background'});assert.equal(core.length+background.length,236);assert.equal(new Set([...core,...background].map(p=>p.id)).size,236);for(const j of journals)assert.equal(C.filter(data,{journal:j.value}).length,j.count);});
test('pagination, empty results and out-of-range pages',()=>{assert.equal(C.paginate(data).items.length,12);assert.equal(C.paginate(data,2,24).start,25);assert.equal(C.paginate(data,999).page,20);assert.equal(C.paginate(data,-9).page,1);assert.equal(C.paginate([],4).total,0);assert.equal(C.paginate([],4).page,1);assert.equal(C.paginate(data,1,999).items.length,12);});
test('source coverage agrees with audit and source URLs are safe',()=>{assert.equal(data.filter(p=>p.pubmed_url).length,audit.pubmed_citations);assert.equal(data.filter(p=>p.doi).length,audit.records_with_doi);for(const p of data)for(const k of ['pubmed_url','doi_url','metadata_url'])if(p[k])assert.ok(C.safeURL(p[k]));assert.equal(C.safeURL('javascript:alert(1)'),null);assert.equal(C.safeURL('data:text/html,test'),null);});
test('malformed data fails rather than using demonstration records',()=>{for(const d of [null,{},[],[{}],[{title:''}]])assert.throws(()=>C.validate(d));assert.ok(!fs.readFileSync(path.join(__dirname,'../assets/publications.js'),'utf8').includes('getFallbackData'));});
test('sorting does not mutate source records',()=>{const original=data.map(p=>p.id);const a=C.sort(data,'newest');assert.ok(Number(a[0].year)>=Number(a.at(-1).year));assert.deepEqual(data.map(p=>p.id),original);});
test('overview groups and links return their displayed record counts',()=>{const s=C.overview(data);assert.equal(s.total,236);assert.equal(s.groups.length,10);const html=fs.readFileSync(path.join(__dirname,'../veterinary/Vet-index.html'),'utf8');for(const g of s.groups){assert.equal(g.count,C.filter(data,{species:g.value}).length);assert.ok(html.includes(`data-species="${g.value}" data-count="${g.count}"`));assert.ok(html.includes(`href="Vet-search.html?species=${encodeURIComponent(g.value)}"`));}assert.equal(s.journalLabels,109);assert.equal(s.institutions,154);assert.equal(s.unspecified,13);});
test('composite species groups deduplicate and preserve unknown records',()=>{const exotic=C.filter(data,{species:'__exotic__'});assert.equal(exotic.length,15);assert.equal(new Set(exotic.map(p=>p.id)).size,15);assert.ok(exotic.every(p=>p.species_tags.some(x=>['Ferret','Rabbit','Other animal'].includes(x))));const other=C.filter(data,{species:'__other_models__'});assert.equal(other.length,21);assert.ok(other.every(p=>!p.species_tags.length||p.species_tags.includes('In vitro')));assert.equal(C.filter(data,{species:C.OTHER}).length,13);});
test('species, institution and author filters combine for real records',()=>{for(const p of data.filter(p=>p.institutions.length&&p.species_tags.length).slice(0,25)){const author=(p.source_authors||p.authors).split(',')[0].replace(/\.$/,'');const f={species:p.species_tags[0],institution:p.institutions[0],author};const found=C.filter(data,f);assert.ok(found.some(x=>x.id===p.id));assert.ok(found.every(x=>x.institutions.includes(f.institution)&&x.species_tags.includes(f.species)));}});
test('author suggestions come from the bibliography and are searchable',()=>{const names=C.authorOptions(data);assert.ok(names.length>100);assert.deepEqual(names,[...names].sort((a,b)=>a.localeCompare(b,'en')));assert.equal(new Set(names.map(C.normalize)).size,names.length);for(const author of names)assert.ok(C.filter(data,{author}).length>0,author);assert.ok(names.includes('Abutarboush R'));const html=fs.readFileSync(path.join(__dirname,'../veterinary/Vet-search.html'),'utf8');assert.ok(html.includes('list="authorOptions"'));assert.ok(html.includes('id="authorOptions"'));});
test('overview snapshot matches the shared search calculation',()=>{const snapshot=JSON.parse(fs.readFileSync(path.join(__dirname,'../veterinary/overview-statistics.json'),'utf8'));for(const [key,value]of Object.entries(C.overview(data)))assert.deepEqual(snapshot[key],value,key);});
test('original-source coverage distinguishes PubMed and publisher-only citations',()=>{assert.equal(data.filter(p=>p.metadata_status==='matched').length,235);assert.equal(data.filter(p=>p.pubmed_url).length,225);assert.equal(data.filter(p=>p.metadata_status==='matched'&&!p.pubmed_url).length,10);assert.equal(data.filter(p=>p.doi).length,217);for(const p of data.filter(p=>p.metadata_status==='matched'))assert.ok(C.safeURL(p.pubmed_url||p.doi_url||p.source_url));});
test('study locations require a source and are not inferred from author affiliations',()=>{const p=data.find(p=>p.id==='bhoc-174');assert.deepEqual(C.studySites(p),['Groote Schuur Hospital']);assert.deepEqual(C.institutions(p),['University of Cape Town']);assert.equal(C.siteOptions(data).length,1);assert.deepEqual(C.filter(data,{site:'Groote Schuur Hospital',institution:'University of Cape Town',author:'Potgieter',species:'Human'}),[p]);assert.equal(C.filter(data,{site:'University of Cape Town'}).length,0);assert.equal(C.filter(data,{site:C.OTHER}).length,235);assert.deepEqual(C.studySites({study_sites:[{institution:'Invented site',source_url:'javascript:alert(1)',locator:'unknown'}]}),[]);for(const site of p.study_sites){assert.ok(C.safeURL(site.source_url));assert.ok(site.locator);assert.ok(site.evidence_note);assert.ok(site.checked);}});
test('unretrieved abstract is retained with secondary evidence, not a fabricated original link',()=>{const p=data.find(p=>p.id==='bhoc-056');assert.equal(p.metadata_status,'not_matched');assert.ok(C.safeURL(p.secondary_source_url));assert.ok(!p.pubmed_url&&!p.doi_url&&!p.link);assert.deepEqual(p.institutions,[]);assert.deepEqual(audit.unmatched_citation_ids,[p.id]);});
test('guinea pigs remain rodents without the false Porcine label',()=>{for(const id of ['bhoc-046','bhoc-156','bhoc-162','bhoc-230']){const p=data.find(p=>p.id===id);assert.ok(p.species_tags.includes('Rodent'));assert.ok(!p.species_tags.includes('Porcine'));assert.ok(p.species_correction_note);}assert.equal(C.filter(data,{species:'Porcine'}).length,38);});

// Execute the production search script against a minimal DOM model. This is not browser/visual QA.
async function searchHarness(query='',failFetch=false){
  const vm=require('node:vm');const html=fs.readFileSync(path.join(__dirname,'../veterinary/Vet-search.html'),'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
  const nodes=new Map(ids.map(id=>[id,{value:'',innerHTML:'',textContent:'',disabled:false,attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,fn){this.listeners[k]=fn;},focus(){}}]));
  nodes.get('sortSelect').value='newest';nodes.get('pageSize').value='12';const errors=[];
  const context={window:{BHOCPublications:C},document:{getElementById:id=>{if(id==='retryLoad'&&!nodes.has(id))nodes.set(id,{addEventListener(){}});return nodes.get(id)||null;}},URLSearchParams,location:{search:query,pathname:'/BHOC-platform/veterinary/Vet-search.html',hash:''},history:{replaceState(a,b,url){context.lastURL=url;}},fetch:async()=>{if(failFetch)throw new Error('Offline');return {ok:true,json:async()=>data};},console:{error:e=>errors.push(e)}};
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/publications.js'),'utf8'),context);await new Promise(resolve=>setImmediate(resolve));return {nodes,context,errors};
}
test('production search handles combined scope, institution and author URL filters',async()=>{const {nodes,context}=await searchHarness('?scope=core&institution=University%20of%20Cape%20Town&author=Potgieter&species=Human');assert.equal(nodes.get('resultSummary').textContent,'1–2 of 2 publications');assert.ok(!nodes.get('results').innerHTML.includes('Confirmed study location:'));assert.ok(nodes.get('results').innerHTML.includes('University of Cape Town'));assert.ok(nodes.get('results').innerHTML.includes('Publisher / Crossref'));assert.ok(!nodes.get('results').innerHTML.includes('Citation verified against <a href="https://europepmc'));assert.ok(context.lastURL.includes('scope=core'));nodes.get('clearBtn').listeners.click();assert.equal(nodes.get('scopeSelect').value,'');assert.equal(nodes.get('resultSummary').textContent,'1–12 of 236 publications');});
test('production search labels secondary-only citations and handles load failures',async()=>{const a=await searchHarness('?q=parasite-induced');assert.ok(a.nodes.get('results').innerHTML.includes('Secondary citation only'));assert.ok(a.nodes.get('results').innerHTML.includes('original citation has not yet been retrieved'));const b=await searchHarness('',true);assert.ok(b.nodes.get('results').innerHTML.includes('No replacement or demonstration records'));assert.equal(b.nodes.get('results').attrs['aria-busy'],'false');assert.equal(b.nodes.get('nextPage').disabled,true);});
