"""Build static, indexable research pages from the JSON catalogue. No server required."""
import json,html,collections,re
from pathlib import Path
from urllib.parse import quote
ROOT=Path(__file__).resolve().parents[1]
e=lambda s:html.escape(str(s or ''),quote=True)
D=json.loads((ROOT/'veterinary/Vet-publications.json').read_text())
def nav(prefix='',active=''):
 links=[('Home','index.html'),('Veterinary','veterinary/Vet-index.html'),('Publications','veterinary/Vet-search.html'),('Institutions','veterinary/institutions.html'),('FDA / EMA','veterinary/Vet-fda-ema.html'),('Science','science/index.html')]
 return '<a class="skip" href="#main">Skip to content</a><nav class="site-nav" aria-label="Main"><div class="shell"><a class="brand" href="'+prefix+'index.html">BHOC</a>'+''.join(f'<a href="{prefix}{path}"'+(' aria-current="page"' if name==active else '')+f'>{name}</a>' for name,path in links)+'</div></nav>'
def page(path,title,desc,body,active='',script=''):
 prefix='../'*len(Path(path).parent.parts);url='https://archiljali.github.io/BHOC-platform/'+path
 t=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} · BHOC</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{e(title)} · BHOC"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><link rel="stylesheet" href="{prefix}assets/site.css"></head><body>{nav(prefix,active)}<main id="main" class="shell">{body}</main><footer class="site-footer"><div class="shell"><span>BHOC · Precision Oxygen Therapeutics</span><a href="{prefix}index.html">Platform</a><a href="{prefix}social-media/linkedin/index.html">LinkedIn resources</a><a href="https://github.com/ArchilJali/BHOC-platform">Source repository</a></div></footer>{script}</body></html>'''
 (ROOT/path).parent.mkdir(parents=True,exist_ok=True);(ROOT/path).write_text(t+'\n')
def intro(k,title,desc):return f'<header class="intro"><span class="eyebrow">{e(k)}</span><h1>{e(title)}</h1><p>{e(desc)}</p></header>'
def select(id,label,values):
 opts=''.join(f'<option value="{e(v)}">{e(v)}</option>' for v in values)
 return f'<label for="{id}">{label}<select id="{id}" name="{id}"><option value="">All</option>{opts}</select></label>'
def card(r):
 ins=r.get('institutions',[]);sp=r.get('species',[]);link=r.get('link','');pdf=r.get('pdf_url','')
 search=' '.join(str(r.get(k,'')) for k in ['id','title','authors','citation','keywords','category','indication','population','model','study_type'])+' '+' '.join(ins)
 # Search aliases help common institution abbreviations without changing attribution.
 aliases={'University of California, Davis':'UC Davis UCD','University of California, San Diego':'UCSD','University of Pennsylvania':'UPenn Penn','University of California, Los Angeles':'UCLA','University of North Carolina at Chapel Hill':'UNC','University Hospital Hamburg-Eppendorf':'UKE Hamburg','Free University of Berlin':'Freie Universität Berlin'}
 search+=' '+' '.join(aliases.get(i,'') for i in ins)+' '+' '.join(sp)
 attrs={'id':r['id'],'title':r['title'],'search':search,'institutions':json.dumps(ins,ensure_ascii=False),'species':json.dumps(sp),'study':r.get('study_type','Not recorded'),'category':r.get('category',''),'year':r.get('year',''),'link':'yes' if link else 'no'}
 a=' '.join(f'data-{k}="{e(v)}"' for k,v in attrs.items())
 badges=''.join(f'<span class="tag">{e(x)}</span>' for x in [r.get('year','Year not recorded')]+sp)
 original=f'<a href="{e(link)}" target="_blank" rel="noopener noreferrer">Original article / DOI ↗</a>' if link else '<span class="muted small">Original link not yet identified</span>'
 pdf_link=f'<a href="{e(pdf)}">Read PDF</a>' if pdf else '<span class="muted small">PDF not yet published</span>'
 institutions=' · '.join(ins) if ins else 'Affiliations not yet verified'
 sources='; '.join(' / '.join(f'{k}: {v}' for k,v in s.items()) for s in r.get('sources',[]))
 return f'''<article class="publication" id="{e(r['id'])}" {a}><div class="chips">{badges}<span class="tag kind">{e(r.get('study_type'))}</span></div><h2>{e(r['title'])}</h2><p class="meta">{e(r.get('authors'))} · {e(r.get('journal'))}</p><p>{e(r.get('summary'))}</p><p class="small"><strong>Institutions:</strong> {e(institutions)}</p><div class="actions">{original}<a href="https://pubmed.ncbi.nlm.nih.gov/?term={quote(r['title'],safe='')}">Search PubMed by title ↗</a>{pdf_link}</div><details><summary>Citation, classification &amp; source notes</summary><p>{e(r.get('citation') or r['title'])}</p><p><strong>Source category:</strong> {e(r.get('category'))} · <strong>Topic:</strong> {e(r.get('indication') or 'Not recorded')}<br><strong>Population / material:</strong> {e(r.get('population') or 'Not recorded')} · <strong>Model:</strong> {e(r.get('model') or 'Not recorded')}</p><p><strong>Summary status:</strong> {e(r.get('summary_status'))}<br><strong>Affiliation status:</strong> {e(r.get('institution_status'))}<br><strong>Link status:</strong> {e(r.get('link_status') or 'Not identified')}</p><p class="muted">{e(sources)}</p></details></article>'''
I=sorted({i for r in D for i in r.get('institutions',[])})
filters=select('institution','Research institution',I).replace('</select>','<option value="missing">Affiliations not yet verified</option></select>')+select('species','Species / material',sorted({x for r in D for x in r.get('species',[])}))+select('study','Study type (source label)',sorted({r.get('study_type','Not recorded') for r in D}))+select('category','Source category',sorted({r.get('category','') for r in D if r.get('category')}))+select('year','Publication year',sorted({r['year'] for r in D if r.get('year')},reverse=True))+'<label for="links">Original article link<select id="links"><option value="">Any status</option><option value="yes">Link available</option><option value="no">Link needs recovery</option></select></label>'
body=intro('Evidence catalogue','Find the study. Follow the source.','Search publications by topic, author, institution or species. Separate bibliographic evidence from regulatory approval.')
body+=f'<div class="metrics"><div class="metric"><strong>{len(D)}</strong><span>catalogue records</span></div><div class="metric"><strong>{len(I)}</strong><span>institutions identified so far</span></div><div class="metric"><strong>{sum(bool(r.get("link")) for r in D)}</strong><span>original links recovered</span></div></div>'
body+='<div id="interactive" hidden><form class="filters" id="filters"><div class="search-row"><label for="q">Search the catalogue<input id="q" type="search" placeholder="Try: UPenn, Oxyglobin, anaemia, perfusion…"></label><button type="submit">Search</button><button class="secondary" type="button" id="clear">Clear</button></div><div class="filter-grid">'+filters+'</div></form><div class="result-toolbar"><p id="stats" role="status" tabindex="-1" aria-live="polite"></p><label for="sort">Sort<select id="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select></label><label for="page-size">Per page<select id="page-size"><option>12</option><option>24</option><option>48</option></select></label></div></div>'
body+='<p class="small muted">Source labels are retained from the supplied catalogue and may require review. Background studies, reviews, clinical reports and experiments are not interchangeable. Institution coverage is incomplete; affiliations do not imply endorsement or a partnership with BHOC.</p><noscript><p class="note">JavaScript is off: all records and original links remain readable below. Use your browser’s Find function.</p></noscript><div id="results">'+''.join(card(r) for r in D)+'</div><div class="empty" id="empty" hidden>No matches. Try fewer filters or a broader keyword.</div><div class="pagination" id="pagination" hidden><button id="previous" class="secondary" type="button">← Previous</button><span id="page-status"></span><button id="next" class="secondary" type="button">Next →</button></div>'
page('veterinary/Vet-search.html','HBOC publication catalogue','Browse HBOC publications by institution, topic, species, year and study type, with citations and original article links.',body,'Publications','<script src="../assets/publications.js" defer></script>')
body=intro('Research institutions','Who studied what?','Institutions identified in author affiliations, linked to the studies and topics represented in this catalogue.')+'<p class="note">This is a partial, source-checked directory. Names identify affiliations in the cited papers, not BHOC partners, endorsements or regulatory approvals. Missing affiliations remain visible in the catalogue.</p><div class="institution-grid">'
for i in I:
 rs=[r for r in D if i in r.get('institutions',[])];body+=f'<section class="panel institution"><span class="eyebrow">{len(rs)} catalogue records</span><h2>{e(i)}</h2><ul>'+''.join(f'<li><a href="Vet-search.html?q={quote(r["id"])}">{e(r["title"])}</a><br><span class="small muted">{e(r.get("year"))} · {e(r.get("indication") or r.get("category"))} · {e(r.get("study_type"))}</span></li>' for r in rs)+f'</ul><a href="Vet-search.html?institution={quote(i)}">Filter by this institution →</a></section>'
body+='</div>';page('veterinary/institutions.html','Research institutions','Research institutions and their HBOC-related studies, with source-checked affiliations and topic links.',body,'Institutions')
body=intro('Veterinary evidence','Oxyglobin & veterinary oxygenation','Product background, regulatory sources, scientific literature and the broader veterinary HBOC research landscape.')
body+='<div class="grid"><section class="panel"><span class="eyebrow">01 / Product</span><h3>What is Oxyglobin?</h3><p>Hemoglobin glutamer-200 (bovine), a polymerized bovine haemoglobin solution. Its historical canine approval is distinct from evidence in other species or with other HBOCs.</p><a href="Vet-fda-ema.html">Read the regulatory record →</a></section><section class="panel"><span class="eyebrow">02 / Literature</span><h3>Search the evidence</h3><p>Find studies by topic, species, author or institution. Each entry keeps its citation and shows which source details still need review.</p><a class="button" href="Vet-search.html">Explore publications</a></section><section class="panel"><span class="eyebrow">03 / Institutions</span><h3>Who studied what?</h3><p>Move from a research institution to its publications and study topics, without confusing affiliation with endorsement.</p><a href="institutions.html">Explore institutions →</a></section></div>'
counts=collections.Counter(s for r in D for s in r.get('species',[]))
body+='<h2>Explore by species</h2><p class="muted">Counts come from the source catalogue’s population field; mixed-species records can appear in more than one group.</p><div class="chips">'+''.join(f'<a class="button secondary" href="Vet-search.html?species={quote(s)}">{e(s)} · {n}</a>' for s,n in sorted(counts.items()))+'</div>'
body+='<h2>Knowledge &amp; documents</h2><div class="grid"><section class="panel"><h3>About this database</h3><p>The section overview, coverage, research principles and guidance are now readable as a website page.</p><a href="Vet-README.html">Read the veterinary overview →</a></section><section class="panel"><h3>FDA &amp; European sources</h3><p>Separate links to original approval, supplemental evidence and European Commission decisions.</p><a href="Vet-fda-ema.html">Open regulatory documents →</a></section><section class="panel"><h3>Business concept</h3><p>The existing veterinary strategy and business concept remain available.</p><a href="business/BHOC-Veterinary-Concept.htm">Read the concept →</a></section><section class="panel"><h3>Reports &amp; source files</h3><p>A document index designed around a brief description followed by the source file.</p><a href="documents.html">Open document index →</a></section></div><div class="note">Educational evidence resource, not prescribing advice. Regulatory records for Oxyglobin do not establish approval for a new BHOC product, human treatment, or every animal species in this catalogue.</div>'
page('veterinary/Vet-index.html','Veterinary HBOC','Oxyglobin veterinary overview, publications, institutions and original FDA and European regulatory documents.',body,'Veterinary')
# Stable directory entry, preserving all existing named URLs.
page('veterinary/index.html','Veterinary evidence hub','Veterinary HBOC evidence and publications.',intro('Veterinary','Veterinary evidence hub','Open the veterinary section.')+'<a class="button" href="Vet-index.html">Enter veterinary hub →</a>','Veterinary')
print('Built catalogue, directory and veterinary pages')
