/* Generate the landing-page overview from the same groups and filters as search. */
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const C=require('../assets/publications-core.js');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=C.validate(JSON.parse(read('veterinary/Vet-publications.json')));
const s=C.overview(data);
const base='https://archiljali.github.io/BHOC-platform/veterinary/';
const fda='https://animaldrugsatfda.fda.gov/adafda/app/search/public/document/downloadFoi/3700';
const eu='https://ec.europa.eu/health/documents/community-register/2021/20211018153269/dec_153269_en.pdf';
const query=g=>'Vet-search.html?species='+encodeURIComponent(g.value);
const note='Counts are records carrying indexed species or model labels, not counts of confirmed treatment studies. A record can appear in several groups; group counts must not be added to obtain the total. Labels may be incomplete.';
const groupNote=`Exotic / other animals combines ferret, rabbit and other-animal labels, counting each record once. It does not imply wildlife use. Other / In vitro includes in-vitro labels and ${s.unspecified} records with no species label.`;
const journalNote='Journal labels are distinct names as stored in the bibliography; full names and abbreviations have not been merged. This is not a verified count of unique journals.';
const stat=(value,label,detail,href)=>`<a class="overview-stat" href="${href}"><strong>${value}</strong><span>${label}</span><small>${detail}</small></a>`;
const max=Math.max(...s.groups.map(g=>g.count),1);
const rows=s.groups.map(g=>`<a class="species-item${g.value==='Human'||g.includeUnspecified?' species-context':''}" href="${query(g)}" data-species="${g.value}" data-count="${g.count}">
  <span class="species-icon" aria-hidden="true">${g.icon}</span><span class="species-name">${esc(g.label)}<span class="species-track" aria-hidden="true"><span style="width:${(100*g.count/max).toFixed(2)}%"></span></span></span><strong>${g.count}<span class="species-arrow" aria-hidden="true"> ↗</span></strong>
</a>`).join('\n');
const main=`<main id="main" class="shell">
<section class="page-intro overview-intro"><div class="eyebrow">Veterinary evidence hub / Oxyglobin &amp; HBOCs</div><h1>Oxygen therapeutics.<br>Evidence in context.</h1><p>Explore the literature by species, follow author institutions and original sources, and distinguish Oxyglobin’s veterinary regulatory history from wider HBOC research.</p><div class="overview-actions"><a class="button" href="Vet-search.html">Explore publications →</a><a class="button secondary" href="#species-distribution">By species ↓</a><a class="button secondary" href="Vet-search.html#institutionSearch">By institution →</a><a class="button secondary" href="Vet-search.html#authorInput">By author →</a><a class="button secondary" href="Vet-search.html#studySiteSelect">By study location →</a></div></section>

<section aria-label="Database statistics" class="overview-stats">
${stat(s.total,'Total publications','Bibliographic records','publication-catalogue.html')}
${stat(s.groups.length,'Species / model groups','Animal, human &amp; in vitro','#species-distribution')}
${stat(s.journalLabels,'Journal labels','Names as recorded; see note','#overview-notes')}
${stat(s.institutions,'Author institutions','Browse the institution directory','Vet-search.html')}
${stat(s.linked,'Source-linked citations',`${s.pubmed} PubMed · ${s.dois} DOI links`,'publication-methodology.html')}
</section>

<div class="overview-grid">
<section class="panel species-panel" id="species-distribution" aria-labelledby="species-heading"><div class="overview-heading"><div><div class="eyebrow">Browse the bibliography</div><h2 id="species-heading">Species Distribution</h2></div><span class="tag">${s.total} total records</span></div><p class="overview-caption">Select a species or model group to open matching publications.</p><div class="species-list">${rows}</div><p class="overview-caption">Human and in-vitro records provide wider research context; they are not veterinary approvals. Bar lengths compare group counts, not percentages of a whole.</p><details class="overview-details" id="overview-notes"><summary>How to interpret these numbers</summary><p>${note}</p><p>${groupNote}</p><p>${journalNote}</p><p><a href="Vet-publications.json">Source bibliography</a> · <a href="publication-methodology.html">Index methodology</a></p></details></section>

<aside class="panel regulatory-overview" aria-labelledby="regulatory-heading"><div class="eyebrow">Named product / Defined indication</div><h2 id="regulatory-heading">Oxyglobin<br>regulatory milestones</h2><p>Haemoglobin glutamer-200 (bovine). The original authorisations concern anaemia in dogs.</p><a class="milestone" href="Vet-fda-ema.html#fda"><span>United States · FDA</span><strong>1998</strong><small>Original approval · NADA 141-067 ↗</small></a><a class="milestone" href="Vet-fda-ema.html#ema"><span>European Union · EC / EMA</span><strong>1999</strong><small>Original marketing authorisation ↗</small></a><p class="overview-caption">An EC amendment followed in 2021. Historical authorisation is not a statement of current supply, approval for other species, or approval of a new BHOC product.</p><a href="Vet-fda-ema.html">Open the official source library →</a></aside>
</div>

<section class="clinical-highlight" aria-labelledby="clinical-heading"><div><div class="eyebrow">Inside the original FDA record</div><h2 id="clinical-heading">A clinical milestone.<br>A defined endpoint.</h2><p>The randomised canine field trial reported treatment success in <strong>22 of 30 Oxyglobin-treated dogs</strong> versus <strong>10 of 34 controls</strong> in the intent-to-treat population.</p><a href="${fda}" target="_blank" rel="noopener noreferrer">Read the FDA study summary, pp. 4–8 ↗</a></div><div><dl class="clinical-stats"><div><dt>Dogs enrolled</dt><dd>64</dd></div><div><dt>Oxyglobin / control</dt><dd>73% <span>/ 29%</span></dd></div><div><dt>Endpoint window</dt><dd>24 <span>hours</span></dd></div></dl><p class="clinical-limit">Success meant no additional oxygen-carrying support for 24 hours; it was not a survival endpoint. The FDA report also documents adverse reactions, including pulmonary oedema. Results apply to this trial and product, not to every species or a future formulation.</p></div></section>

<div class="quick-grid"><article class="panel quick-card"><span class="eyebrow">01 / Sources</span><h2>Find the people behind the paper.</h2><p>Search ${s.institutions} author institutions and follow article-level affiliation evidence. Select a confirmed study location separately; this review is still partial.</p><a class="button secondary" href="Vet-search.html">Browse institutions →</a><a href="Vet-search.html#authorInput">Find publications by author →</a><a href="Vet-search.html?site=Groote%20Schuur%20Hospital">Confirmed location: Groote Schuur →</a></article><article class="panel quick-card"><span class="eyebrow">02 / Scope</span><h2>Read each finding in context.</h2><p>The bibliography includes studies, reviews, case reports and background literature. Citation matching is not an assessment of efficacy or study quality. ${s.siteRecords} record currently has independently sourced study-location evidence.</p><a class="button secondary" href="publication-methodology.html">Understand the index →</a></article><article class="panel quick-card"><span class="eyebrow">03 / Development</span><h2>Precision oxygen therapeutics.</h2><p>Explore the proposed BHOC veterinary framework: supporting the oxygen-delivery function of blood while recognising its other essential functions.</p><a class="button secondary" href="business/BHOC-Veterinary-Concept.htm">Read the concept →</a></article></div>
<p class="notice">Author affiliations are not institutional endorsements or an exhaustive list of study sites. Historical Oxyglobin approvals do not establish approval of a new BHOC formulation or human use. <a href="Vet-README.html">Section guide</a> · <a href="publication-catalogue.html">Full citation catalogue</a>.</p>
</main>`;
const table=(absolute=false)=>`| Species / model group | Indexed publications |\n| :--- | ---: |\n`+s.groups.map(g=>`| ${g.icon} [${g.label}](${absolute?base:''}${query(g)}) | ${g.count} |`).join('\n')+`\n| **Total bibliography (not the sum of groups)** | **${s.total}** |`;
const metrics=`| Metric | Value |\n| :--- | :--- |\n| **Total Publications** | **${s.total} bibliographic records** |\n| **Species / Model Groups** | ${s.groups.length} groups, including human and in-vitro context |\n| **Journals** | ${s.journalLabels} distinct journal labels; abbreviations not merged |\n| **Author Institutions** | ${s.institutions} labels from article-level affiliations |\n| **Original Citation Links** | ${s.linked} original citations: ${s.pubmed} PubMed; ${s.dois} DOI links |\n| **FDA — Oxyglobin** | [Original approval: 12 January 1998; dogs](${fda}) |\n| **EU / EMA — Oxyglobin** | [Original EU authorisation: 1999; amendment: 2021](${eu}) |`;
const landing=`# Veterinary evidence hub\n\n## Oxyglobin · HBOC literature · Precision oxygen therapeutics\n\n[**Open the Veterinary website →**](${base}Vet-index.html) · [Publication explorer](${base}Vet-search.html) · [FDA & EMA records](${base}Vet-fda-ema.html)\n\nExplore species, author institutions and original citations. Historical Oxyglobin approvals, broader research and the proposed BHOC veterinary concept are presented separately.\n\n## Database at a glance\n\n${metrics}\n\n${journalNote}\n\n## Species Distribution\n\nChoose a group to open its filtered publication list on the website.\n\n${table(true)}\n\n${note}\n\n${groupNote}\n\n## A clinical milestone in the FDA record\n\nIn the randomised field trial of 64 anaemic dogs, treatment success was reported in **22/30 (73%)** Oxyglobin-treated dogs versus **10/34 (29%)** controls (intent-to-treat population). Success meant no additional oxygen-carrying support for 24 hours, not survival. Adverse reactions, including pulmonary oedema, were reported. [Read the original FDA summary, pp. 4–8](${fda}).\n\n## Explore the section\n\n- [Choose or search an author](${base}Vet-search.html#authorInput)\n- [Confirmed study locations — partial review](${base}Vet-search.html#studySiteSelect)\n- [Author institutions and original publications](${base}Vet-search.html)\n- [Source matching, species labels and evidence limits](${base}publication-methodology.html)\n- [Veterinary development concept](${base}business/BHOC-Veterinary-Concept.htm)\n- [Detailed section guide](Vet-README.md)\n- [Structured bibliography](Vet-publications.json)\n\n**Scope:** This is a bibliography, not a systematic review or proof that all listed products work in all species. Institutions are author affiliations, not BHOC endorsements. The historical Oxyglobin authorisations concern dogs and do not establish human-use approval or approval of a new BHOC formulation. Current supply and prescribing status require current official records.\n\nScientific and educational information. Not clinical advice. Metadata snapshot: 28 August 2026.\n`;
let guide=read('veterinary/Vet-README.md');
guide=guide.replace(/## Oxyglobin — The Only FDA-Approved HBOC for Veterinary Use/,'## Oxyglobin — Veterinary Regulatory History and HBOC Research');
guide=guide.replace(/the most comprehensive collection of peer-reviewed publications, regulatory documents, and scientific resources/,'a source-linked collection of publications, regulatory documents, and scientific resources');
guide=guide.replace(/\*\*200\+ peer-reviewed publications\*\*/g,`**${s.total} bibliographic records**`).replace(/200\+/g,String(s.total));
guide=guide.replace(/## 📊 Database Statistics[\s\S]*?\n---/,`## 📊 Database Statistics\n\n${metrics}\n\n${journalNote}\n\nHistorical authorisations concern Oxyglobin for dogs; they are not approval of a new BHOC product or a claim of current availability.\n\n---`);
guide=guide.replace(/## 🌍 Species Distribution[\s\S]*?\n---/,`## 🌍 Species Distribution\n\n${table(true)}\n\n${note}\n\n${groupNote}\n\n[Source data](Vet-publications.json) · [Methodology](${base}publication-methodology.html)\n\n---`);
// The website guide is a concise HTML counterpart; the full guide remains on GitHub.
const guideHTML=`<main id="main" class="shell reading"><section class="page-intro"><div class="eyebrow">Veterinary / Section guide</div><h1>Start with the evidence.</h1><p>${s.total} records, ${s.institutions} institution labels and ${s.groups.length} species / model groups. <a href="Vet-index.html">Open the Veterinary overview →</a></p></section><section class="panel"><h2>Database statistics</h2><dl class="facts"><div><dt>Publications</dt><dd>${s.total} records</dd></div><div><dt>Indexed citations</dt><dd>${s.linked} original citations / ${s.pubmed} PubMed / ${s.dois} DOI</dd></div><div><dt>Institutions</dt><dd>${s.institutions} labels</dd></div><div><dt>Journals</dt><dd>${s.journalLabels} journal labels</dd></div></dl><p>${journalNote}</p><h2 id="species-distribution">Species Distribution</h2><table><thead><tr><th scope="col">Species / model</th><th scope="col">Indexed publications</th></tr></thead><tbody>${s.groups.map(g=>`<tr><th scope="row"><a href="${query(g)}">${esc(g.label)}</a></th><td>${g.count}</td></tr>`).join('')}</tbody><tfoot><tr><th scope="row">Total bibliography</th><td>${s.total}</td></tr></tfoot></table><p>${note}</p><p>${groupNote}</p><h2>Regulatory history</h2><p>Oxyglobin: <a href="Vet-fda-ema.html#fda">FDA original approval in 1998</a> and <a href="Vet-fda-ema.html#ema">EU original authorisation in 1999</a>. These records concern dogs, not every species in the index or a new BHOC formulation.</p><h2>Go deeper</h2><p><a href="Vet-search.html">Publication explorer</a> · <a href="publication-methodology.html">Index methodology</a> · <a href="business/BHOC-Veterinary-Concept.htm">Development concept</a> · <a href="https://github.com/ArchilJali/BHOC-platform/blob/main/veterinary/Vet-README.md">Full Markdown guide on GitHub</a>.</p></section></main>`;
const outputs={
  'veterinary/Vet-index.html':read('veterinary/Vet-index.html').replace(/<main\b[\s\S]*?<\/main>/,main),
  'veterinary/README.md':landing,
  'veterinary/Vet-README.md':guide,
  'veterinary/Vet-README.html':read('veterinary/Vet-README.html').replace(/<main\b[\s\S]*?<\/main>/,guideHTML),
  'veterinary/overview-statistics.json':JSON.stringify({snapshot:'2026-08-28',...s,notes:{counts:note,groups:groupNote,journals:journalNote}},null,2)+'\n'
};
let stale=false;
for(const [file,content] of Object.entries(outputs)){
  if(process.argv.includes('--check')){if(!fs.existsSync(path.join(root,file))||read(file)!==content){console.error('Stale overview: '+file);stale=true;}}
  else fs.writeFileSync(path.join(root,file),content);
}
if(stale)process.exitCode=1;
else console.log(`${process.argv.includes('--check')?'Verified':'Generated'} ${Object.keys(outputs).length} Veterinary overview files: ${s.total} records / ${s.groups.length} groups.`);
