"""Generate one independent, source-linked HTML summary for each Biopure report."""
from pathlib import Path
import html,json,re,xml.etree.ElementTree as ET
R=Path(__file__).resolve().parents[1];BASE='https://archiljali.github.io/BHOC-platform/'
e=html.escape
DATA={
2001:{'title':'Biopure 2001: Oxyglobin, Hemopure & Oxygen Therapeutics','headline':'From oxygen science to clinical milestones.','desc':'Biopure’s 2001 annual report: Oxyglobin adoption, Hemopure’s South African approval, Carl W. Rausch and the development of oxygen therapeutics.','metrics':[('100,000+','Oxyglobin units sold since 1998','4'),('22','Hemopure clinical trials reported','8'),('800+','patients given Hemopure in trials','8')],
'items':[
('A veterinary product in clinical use','The report records more than 100,000 Oxyglobin units sold since launch, following US FDA approval in 1998 and European Commission approval in 1999. This documents adoption of an oxygen-carrying drug for canine anemia; unit sales are not a count of patients or successful treatments.','4'),
('A defined human indication in South Africa','Biopure reports Hemopure approval in April 2001 for acutely anemic adult surgical patients, to eliminate, reduce or delay allogeneic red blood cell transfusion. This was a jurisdiction-specific milestone, not US approval.','6'),
('A substantial development programme','The report describes 22 clinical trials, over 1,300 enrolled participants and more than 800 Hemopure recipients. It reports completion of Phase III programmes and preparation of a US application. Trial participation alone does not establish safety or benefit.','8')],
'importance':'The historical achievement was making oxygen delivery a manufactured therapeutic function, supported by clinical development, regulatory work and veterinary use. The report’s “Oxygen Bridge” concept framed temporary oxygen-carrying support around patient need.',
'person':'Carl W. Rausch, a Biopure co-founder, was Chairman and Chief Executive Officer in the 2001 report. His shareholder letter describes the scientific, manufacturing and regulatory programme.',
'personpage':'3','limits':'The US Hemopure application was still being prepared. Manufacturing validation and further financing remained necessary; planned facilities and projected profitability were forward-looking statements, not completed achievements.','limitpage':'3',
'perspective':'For BHOC and Precision Oxygenation Therapeutics, this history helps frame a practical question: which oxygen-delivery function does a patient need, and when? Relevance to emergency care is a research and development question; this report does not establish an emergency-use indication.'},
2002:{'title':'Biopure 2002: Oxyglobin Adoption & Hemopure Development','headline':'Scaling the evidence. Building the capability.','desc':'Biopure’s 2002 annual report: 115,000+ cumulative Oxyglobin units, Hemopure FDA review, manufacturing, emergency research and Carl W. Rausch.','metrics':[('115,000+','Oxyglobin units sold since launch','15'),('180+','preclinical studies reported','14'),('75,000','Hemopure units/year capacity reported','6')],
'items':[
('A major regulatory submission','Biopure filed its Hemopure biologic license application on 31 July 2002; FDA accepted it for review in October. Acceptance was a development milestone, not marketing approval.','6'),
('Veterinary experience with a human story','The report describes Oxyglobin treatment of Fresno police dog Saxon after a gunshot injury in August 2002. A letter from the police chief credits its role in his recovery. This is a reported case and testimonial, not proof of a general survival benefit.','15'),
('Manufacturing and emergency research','Biopure reported annual capacity of up to 75,000 Hemopure units and a $908,900 US Army grant for trauma research. Research funding and proposed trauma trials did not constitute approval for prehospital or battlefield use.','14')],
'importance':'The report connects oxygen therapeutics with the practical demands of manufacturing, clinical development and medical readiness. Its reported room-temperature product strategy explains interest in emergency logistics; clinical benefit still requires indication-specific evidence.',
'person':'Carl W. Rausch remained a Biopure co-founder and was listed as Vice Chairman and Chief Technology Officer. Thomas A. Moore was President and Chief Executive Officer; the report credits Rausch and the wider team’s contributions.',
'personpage':'16','limits':'The report also describes supply backorders, slower-than-planned progress and an auditor’s going-concern note. It includes early-2003 updates: these should not be mistaken for events completed during fiscal 2002.','limitpage':'9',
'perspective':'For BHOC and Precision Oxygenation Therapeutics, the lesson is practical: oxygen-delivery science must be matched by manufacturing, evidence, regulatory clarity and dependable supply. Historical Biopure achievements are not evidence of approval or efficacy for a present-day BHOC product.'}}
CSS=''' .report-hero{display:grid;grid-template-columns:minmax(0,1fr) 240px;gap:38px;align-items:center;padding:34px 0 28px;border-bottom:1px solid var(--line)}.report-hero h1{font:normal clamp(30px,4vw,48px)/1.1 Georgia,serif;margin:12px 0 16px}.report-hero p{color:var(--muted)}.report-cover{width:100%;height:235px;object-fit:contain;background:#fff;border:1px solid var(--line);box-shadow:0 8px 20px #193e3312}.report-year{font:normal 21px Georgia;color:var(--teal)}.report-metrics{display:grid;grid-template-columns:repeat(3,1fr);margin:24px 0;border:1px solid var(--line);background:white}.report-metrics>div{padding:18px;border-right:1px solid var(--line)}.report-metrics>div:last-child{border:0}.report-metrics strong{display:block;font:32px/1.2 Georgia,serif;color:var(--teal)}.report-metrics span{display:block;font-size:13px;margin-top:7px}.report-columns{display:grid;grid-template-columns:1.25fr 1fr;gap:30px}.report-columns h2{font-size:27px;margin-top:8px}.milestone{border-bottom:1px solid var(--line);padding:0 0 10px;margin-bottom:14px}.milestone h3{font-size:17px;margin:0 0 6px}.milestone p,.report-aside p{font-size:14px;line-height:1.6}.source{white-space:nowrap;font-size:11px}.report-aside{background:#e8eeea;padding:22px;border-radius:5px;align-self:start}.report-aside h3{font-size:16px;margin:16px 0 6px}.report-aside h3:first-child{margin-top:0}.report-tags{font-size:12px;color:var(--teal);line-height:2;word-spacing:8px}.report-byline{font-size:12px;color:var(--muted);margin-top:10px}.report-downloads{margin:24px 0 0;padding:20px;border:1px solid var(--line);background:white}.report-downloads h2{font-size:25px;margin:0 0 12px}.report-downloads p{font-size:13px;margin:12px 0 0}@media(max-width:700px){.report-hero{grid-template-columns:1fr;gap:15px}.report-cover{height:180px}.report-columns{grid-template-columns:1fr}.report-metrics strong{font-size:25px}.report-metrics>div{padding:12px}.report-hero h1{font-size:34px}}@media print{.report-hero{grid-template-columns:1fr 130px;padding:12px 0}.report-cover{height:130px}.report-hero h1{font-size:28px}.report-columns{gap:20px}.report-columns p{font-size:10px}.report-metrics{margin:12px 0}.report-downloads,.site-footer,.report-tags{display:none}.report-aside{padding:12px}body{font-size:11px}.shell{padding:0}.report-columns h2{font-size:20px}}'''
(R/'assets/reports.css').write_text(CSS+'\n')
def source(year,page):return f'<a class="source" href="files/biopure-annual-report-{year}.pdf#page={page}" aria-label="{year} report, PDF page {page}">[PDF p. {page}]</a>'
for y,d in DATA.items():
 path=f'reports/biopure-annual-report-{y}.html';url=BASE+path;pdf=f'files/biopure-annual-report-{y}.pdf';cover=f'images/biopure-{y}-cover.jpg';other=2002 if y==2001 else 2001
 schema={'@context':'https://schema.org','@type':'Article','headline':d['title'],'description':d['desc'],'inLanguage':'en','mainEntityOfPage':url,'url':url,'image':BASE+f'reports/{cover}','author':{'@type':'Person','name':'Archil Jaliashvili'},'publisher':{'@type':'Organization','name':'BHOC Platform'},'dateModified':'2026-08-28','keywords':['BHOC','Oxyglobin','Hemopure','oxygenation','transfusion medicine','hemoglobin-based oxygen carriers','precision oxygenation therapeutics','emergency medicine'],'mentions':[{'@type':'Person','name':'Carl W. Rausch'},{'@type':'Organization','name':'Biopure Corporation'}],'citation':{'@type':'Report','name':f'Biopure Corporation Annual Report {y}','author':{'@type':'Organization','name':'Biopure Corporation'},'url':BASE+'reports/'+pdf,'encoding':{'@type':'MediaObject','contentUrl':BASE+'reports/'+pdf,'encodingFormat':'application/pdf'}}}
 nav='<nav class="site-nav" aria-label="Main navigation"><div class="shell"><a class="brand" href="../index.html">BHOC</a><a href="../veterinary/Vet-index.html">Veterinary</a><a href="../veterinary/Vet-search.html">Publications</a><a href="../veterinary/documents.html">Documents</a><a href="../veterinary/Vet-fda-ema.html">FDA / EMA</a></div></nav>'
 body=f'<header class="report-hero"><div><span class="eyebrow">Historical evidence / Annual report</span><p class="report-year">Biopure Corporation · {y}</p><h1>{d["headline"]}</h1><p>{e(d["desc"])}</p><div class="report-byline">BHOC perspective · Archil Jaliashvili<br>Summary of a company report; historical claims are attributed to Biopure.</div></div><a href="{pdf}" aria-label="Open full Biopure {y} report"><img class="report-cover" src="{cover}" width="240" height="235" alt="Cover of Biopure Corporation’s {y} Annual Report on oxygen therapeutics"></a></header>'
 body+='<section class="report-metrics" aria-label="Key figures reported by Biopure">'+''.join(f'<div><strong>{e(n)}</strong><span>{e(label)}</span>{source(y,p)}</div>' for n,label,p in d['metrics'])+'</section><div class="report-columns"><section><h2>Key achievements</h2>'
 for title,text,p in d['items']:body+=f'<article class="milestone"><h3>{e(title)}</h3><p>{e(text)} {source(y,p)}</p></article>'
 body+='</section><aside class="report-aside"><h3>Why this matters</h3><p>'+e(d['importance'])+'</p><h3>People behind the programme</h3><p>'+e(d['person'])+' '+source(y,d['personpage'])+'</p><h3>Read the achievement in context</h3><p>'+e(d['limits'])+' '+source(y,d['limitpage'])+'</p></aside></div>'
 body+='<section class="note"><strong>BHOC perspective · Precision Oxygenation Therapeutics</strong><p style="margin:8px 0 0">'+e(d['perspective'])+'</p></section>'
 body+=f'<section class="report-downloads"><h2>Read the original report</h2><div class="actions"><a class="button" href="{pdf}">Open {y} annual report · PDF</a><a class="button secondary" href="{pdf}" download>Download PDF</a><a href="biopure-annual-report-{other}.html">Read the separate {other} summary →</a></div><p>The uploaded report is reproduced unchanged. Page citations use the PDF page number, including front matter. Original report: Biopure Corporation. Commentary: BHOC Platform.</p></section>'
 body+='<p class="report-tags" aria-label="Topics and hashtags">#BHOC #Oxyglobin #Hemopure #OxygenTherapeutics #TissueOxygenation #TransfusionMedicine #EmergencyMedicine #PrecisionOxygenationTherapeutics</p>'
 text=f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(d["title"])}</title><meta name="description" content="{e(d["desc"])}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="author" content="Archil Jaliashvili"><link rel="canonical" href="{url}"><meta property="og:type" content="article"><meta property="og:title" content="{e(d["title"])}"><meta property="og:description" content="{e(d["desc"])}"><meta property="og:url" content="{url}"><meta property="og:site_name" content="BHOC Platform"><meta property="og:image" content="{BASE}reports/{cover}"><meta property="og:image:alt" content="Biopure annual report {y} cover"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{e(d["title"])}"><meta name="twitter:description" content="{e(d["desc"])}"><meta name="twitter:image" content="{BASE}reports/{cover}"><meta name="twitter:image:alt" content="Biopure annual report {y} cover"><link rel="stylesheet" href="../assets/site.css"><link rel="stylesheet" href="../assets/reports.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False).replace("<","\\u003c")}</script></head><body><a class="skip" href="#main">Skip to content</a>{nav}<main class="shell" id="main">{body}</main><footer class="site-footer"><div class="shell"><span>Historical evidence, not medical advice or a present-day product approval.</span><a href="../veterinary/documents.html">All documents</a></div></footer></body></html>'
 (R/path).write_text(text+'\n')
# Add discoverable entry links without replacing existing page content.
for path,prefix in [('index.html','reports/'),('veterinary/documents.html','../reports/'),('veterinary/Vet-index.html','../reports/'),('science/index.html','../reports/')]:
 p=R/path;t=p.read_text();t=re.sub(r'<!-- annual-reports:start -->.*?<!-- annual-reports:end -->','',t,flags=re.S)
 block='<section id="annual-reports"><h2>Biopure annual reports</h2><p>Two years. Two separate summaries. Key milestones, context and the original PDFs.</p><div class="grid">'+''.join(f'<article class="panel"><h3>Biopure {y}</h3><p>{e(d["headline"])}</p><a href="{prefix}biopure-annual-report-{y}.html">Read {y} summary &amp; report →</a></article>' for y,d in DATA.items())+'</div></section>'
 t=t.replace('</main>','<!-- annual-reports:start -->'+block+'<!-- annual-reports:end --></main>')
 t=t.replace('No annual reports have been supplied yet. Individual article PDFs have not been published in this update.','Biopure annual reports for 2001 and 2002 are available below, each with its own summary and original PDF. Individual research article PDFs remain unpublished.')
 p.write_text(t)
# Crawlable sitemap; do not create an ineffective project-subdirectory robots.txt.
ns='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',ns);sitemap=ET.Element('{'+ns+'}urlset')
for p in sorted(R.rglob('*.html')):
 t=p.read_text();m=re.search(r'<link rel="canonical" href="([^"]+)"',t)
 if m and m.group(1).startswith(BASE):u=ET.SubElement(sitemap,'{'+ns+'}url');ET.SubElement(u,'{'+ns+'}loc').text=m.group(1)
ET.ElementTree(sitemap).write(R/'sitemap.xml',encoding='utf-8',xml_declaration=True)
print('Built two independent report pages, four entry points and sitemap')
