const fs = require('fs');

const mdPath = 'historical-sources/biopure-standing-on-the-shoulders-of-giants/article.md';
const htmlPath = 'historical-sources/biopure-standing-on-the-shoulders-of-giants/index.html';
let md = fs.readFileSync(mdPath, 'utf8');
let html = fs.readFileSync(htmlPath, 'utf8');

const qualityMd = `### 4.1. Manufacturing Quality Is Part of the Product

For an injectable cell-free hemoglobin biologic, purification and manufacturing control are not secondary to the molecule. They are part of the product definition and part of regulatory acceptability. Biopure itself explained this directly in SEC filings: Hemopure was classified as a biologic, and a change in manufacturing process could be considered by FDA to produce an altered or potentially different product.[18](#ref-18)

Early cell-free hemoglobin work also showed why this matters biologically. Endotoxin, stromal phospholipids and residual proteins can confound attribution of inflammatory toxicity to hemoglobin itself. Quantitative endotoxin assays later identified lipopolysaccharide contamination in some early modified-hemoglobin production runs and allowed sources to be identified and controlled.[19](#ref-19),[20](#ref-20)

Endotoxin cannot be assigned retrospectively as the sole cause of HBOC toxicity. Our interpretation is narrower: inadequate control of endotoxin or other residual contaminants may have contributed materially to toxicity in some early preparations and may have made it harder to separate product biology from process-related inflammation. Product-specific NO reactivity, oxidation, methemoglobin formation, heme release, molecular-size distribution and oxygen affinity remain important.

The regulatory history of Oxyglobin makes the manufacturing requirement concrete. FDA inspected Biopure's facilities for compliance with good manufacturing practices, and European regulators also inspected the facilities before Oxyglobin marketing authorization.[18](#ref-18),[21](#ref-21) For a hemoglobin oxygen carrier, manufacturing consistency is part of the medicine, not an administrative detail.

`;

const governanceMd = `### 6.1. What Failed at Biopure: Technology, Governance, Regulation and Capital

The collapse of Biopure Corporation should not be reduced to a simple statement that the technology failed. Oxyglobin had U.S. and European veterinary authorization, Hemopure had South African human authorization, and Biopure had built an industrial manufacturing platform. At the same time, the U.S. human program had real clinical and regulatory problems.

The public-company history added another layer. Biopure's July 1999 IPO was not the clean blockbuster launch sometimes implied in later retellings. An SEC case concerning the underwriter described Biopure as a "cold" IPO for which the offering size and proposed price range were reduced and final pricing was delayed.[22](#ref-22) Biopure later traded at a market capitalization above $1 billion according to a later SEC-filed successor-company prospectus, but that is not the same as an IPO valuation.[23](#ref-23)

Leadership also changed. Carl W. Rausch, co-founder and CEO from 1984 to 2002, moved to Vice Chairman and Chief Technology Officer in 2002; Thomas A. Moore became President and CEO.[18](#ref-18) The public record establishes the transition, but it does not prove that the board removed Rausch because of a conflict of interests or that the leadership change alone caused the later failure.

In 2003 FDA placed the proposed trauma program on clinical hold and raised serious questions about the orthopedic-surgery application. SEC later brought enforcement actions alleging that Biopure and executives made misleading disclosures about material FDA developments while the company was raising capital. Biopure settled the SEC case in 2006 without admitting or denying the allegations and agreed to retain an independent consultant to review disclosure and compliance procedures.[24](#ref-24),[25](#ref-25)

Financing pressure then became severe. In 2009 Biopure entered bankruptcy proceedings and sold substantially all operating assets to OPK Biotech.[26](#ref-26) There is no primary-source basis for saying that FDA "revoked Biopure's GMP license." SEC filings instead show FDA GMP inspections of the manufacturing facilities and continued manufacturing activity.[18](#ref-18)

The more defensible historical conclusion is that governance, disclosure, regulatory strategy, clinical risk and capital constraints all shaped Biopure's outcome. The failure of the corporation was not identical to disappearance of the underlying technology. But it would also be inaccurate to dismiss the U.S. regulatory setbacks as politics or finance alone.

`;

if (!md.includes('### 4.1. Manufacturing Quality Is Part of the Product')) {
  md = md.replace('\n## 5. Regulatory and Clinical Translation', '\n' + qualityMd + '## 5. Regulatory and Clinical Translation');
}
if (!md.includes('### 6.1. What Failed at Biopure')) {
  md = md.replace('\n## 7. Historical Significance and Limitations', '\n' + governanceMd + '## 7. Historical Significance and Limitations');
}
if (!md.includes('**Last updated:** 12 Sep 2026')) {
  md = md.replace('**Prepared:** August 2026', '**Prepared:** August 2026  \n**Last updated:** 12 Sep 2026');
}
if (!md.includes('<a id="ref-18"></a>')) {
  const refs = `\n<a id="ref-18"></a>**18.** Biopure Corporation. Form 10-K and executive/manufacturing disclosures: biologics are defined by manufacturing process and composition; FDA GMP inspection history; Carl W. Rausch and Thomas A. Moore executive roles. U.S. Securities and Exchange Commission. [SEC filing](https://www.sec.gov/Archives/edgar/data/815508/000095013504000426/b49311bce10vk.htm)\n\n<a id="ref-19"></a>**19.** Feola M, Simoni J, Canizaro PC. Quality control of hemoglobin solutions: purity before modification. *Artificial Organs*. 1991. [PubMed](https://pubmed.ncbi.nlm.nih.gov/1867535/)\n\n<a id="ref-20"></a>**20.** Production of modified crosslinked cell-free hemoglobin for human use: quantitative determination of endotoxin contamination. [PubMed](https://pubmed.ncbi.nlm.nih.gov/8259598/)\n\n<a id="ref-21"></a>**21.** European Medicines Agency. Oxyglobin regulatory history and pre-authorisation manufacturing inspection. [EMA](https://www.ema.europa.eu/en/documents/procedural-steps/oxyglobin-epar-procedural-steps-taken-authorisation_en.pdf)\n\n<a id="ref-22"></a>**22.** U.S. Securities and Exchange Commission. J.P. Morgan Securities Inc. litigation release describing the July 1999 Biopure offering as a "cold" IPO. [SEC Litigation Release No. 18385](https://www.sec.gov/enforcement-litigation/litigation-releases/lr-18385)\n\n<a id="ref-23"></a>**23.** SEC-filed successor-company prospectus discussing Biopure's later market capitalization and product history. This retrospective source is used only for the later market-capitalization statement, not as an IPO valuation. [SEC filing](https://www.sec.gov/Archives/edgar/data/1615647/000149315222011184/forms-1.htm)\n\n<a id="ref-24"></a>**24.** U.S. Securities and Exchange Commission. SEC Charges Massachusetts Biotechnology Company and Executives with Securities Fraud. 14 Sep 2005. [SEC Litigation Release No. 19376](https://www.sec.gov/enforcement-litigation/litigation-releases/lr-19376)\n\n<a id="ref-25"></a>**25.** U.S. Securities and Exchange Commission. SEC Settles Civil Injunctive Action Against Biopure Corporation and Its General Counsel. 12 Sep 2006. [SEC Litigation Release No. 19825](https://www.sec.gov/enforcement-litigation/litigation-releases/lr-19825)\n\n<a id="ref-26"></a>**26.** Biopure Corporation. Form 8-K, 18 Aug 2009: bankruptcy auction and sale of substantially all operating assets to OPK Biotech LLC. [SEC filing](https://www.sec.gov/Archives/edgar/data/815508/000119312509180106/d8k.htm)\n`;
  md = md.replace('\n## Copyright and Permissions', refs + '\n## Copyright and Permissions');
}
md = md.replaceAll('—','-').replaceAll('–','-');
fs.writeFileSync(mdPath, md);

// HTML mirror.
html = html.replace('content="2026-08-29">\n  <link rel="stylesheet"', 'content="2026-09-12">\n  <link rel="stylesheet"');
html = html.replace('"dateModified": "2026-08-29"', '"dateModified": "2026-09-12"');
if (!html.includes('<span class="byline__label">Updated</span>')) {
  html = html.replace('<span class="byline__label">Reading time</span>', '<span class="byline__label">Updated</span>\n          <time datetime="2026-09-12">12 Sep 2026</time>\n        </div>\n        <div>\n          <span class="byline__label">Reading time</span>');
}
const qualityHtml = `        <h3 id="4-1-manufacturing-quality-is-part-of-the-product">4.1. Manufacturing Quality Is Part of the Product</h3>\n        <p>For an injectable cell-free hemoglobin biologic, purification and manufacturing control are not secondary to the molecule. They are part of the product definition and regulatory acceptability. Biopure itself explained this in SEC filings: Hemopure was classified as a biologic, and a manufacturing-process change could be considered by FDA to produce an altered or potentially different product.<a href="#ref-18">18</a></p>\n        <p>Early cell-free hemoglobin work also showed why this matters biologically. Endotoxin, stromal phospholipids and residual proteins can confound attribution of inflammatory toxicity to hemoglobin itself. Quantitative endotoxin assays identified lipopolysaccharide contamination in some early modified-hemoglobin production runs and allowed sources to be identified and controlled.<a href="#ref-19">19</a>,<a href="#ref-20">20</a></p>\n        <p>Endotoxin cannot be assigned retrospectively as the sole cause of HBOC toxicity. Our interpretation is narrower: inadequate control of endotoxin or other residual contaminants may have contributed materially to toxicity in some early preparations. Product-specific NO reactivity, oxidation, methemoglobin formation, heme release, molecular-size distribution and oxygen affinity remain important.</p>\n        <p>The Oxyglobin regulatory history makes the manufacturing requirement concrete. FDA inspected Biopure facilities for GMP compliance, and European regulators also inspected the facilities before Oxyglobin marketing authorization.<a href="#ref-18">18</a>,<a href="#ref-21">21</a> For a hemoglobin oxygen carrier, manufacturing consistency is part of the medicine, not an administrative detail.</p>\n`;
if (!html.includes('id="4-1-manufacturing-quality-is-part-of-the-product"')) {
  html = html.replace(/\s*<h2 id="5-regulatory-and-clinical-translation">/, '\n' + qualityHtml + '        <h2 id="5-regulatory-and-clinical-translation">');
}
const governanceHtml = `        <h3 id="6-1-what-failed-at-biopure-technology-governance-regulation-and-capital">6.1. What Failed at Biopure: Technology, Governance, Regulation and Capital</h3>\n        <p>The collapse of Biopure Corporation should not be reduced to a simple statement that the technology failed. Oxyglobin had U.S. and European veterinary authorization, Hemopure had South African human authorization, and Biopure had built an industrial manufacturing platform. At the same time, the U.S. human program had real clinical and regulatory problems.</p>\n        <p>Biopure's July 1999 IPO was not the clean blockbuster launch sometimes implied in later retellings. An SEC case concerning the underwriter described it as a "cold" IPO for which the offering size and proposed price range were reduced and final pricing was delayed.<a href="#ref-22">22</a> A later SEC-filed successor prospectus says Biopure subsequently traded at a market capitalization above $1 billion, but that is not the same as an IPO valuation.<a href="#ref-23">23</a></p>\n        <p>Leadership changed in 2002. Carl W. Rausch moved from CEO to Vice Chairman and Chief Technology Officer, while Thomas A. Moore became President and CEO.<a href="#ref-18">18</a> The public record establishes that transition, but it does not establish that a board conflict caused the company's later failure.</p>\n        <p>In 2003 FDA placed the proposed trauma program on clinical hold and raised serious questions about the orthopedic-surgery application. SEC later brought enforcement actions alleging misleading disclosure of material FDA developments while the company was raising capital. Biopure settled in 2006 without admitting or denying the allegations and agreed to retain an independent compliance consultant.<a href="#ref-24">24</a>,<a href="#ref-25">25</a></p>\n        <p>Financing pressure later became severe. In 2009 Biopure entered bankruptcy proceedings and sold substantially all operating assets to OPK Biotech.<a href="#ref-26">26</a> There is no primary-source basis for saying FDA revoked a Biopure GMP license. SEC filings instead document GMP inspections and continued manufacturing activity.<a href="#ref-18">18</a></p>\n        <p>The more defensible historical conclusion is that governance, disclosure, regulatory strategy, clinical risk and capital constraints all shaped Biopure's outcome. The failure of the corporation was not identical to disappearance of the underlying technology. But the U.S. regulatory setbacks cannot be dismissed as politics or finance alone.</p>\n`;
if (!html.includes('id="6-1-what-failed-at-biopure-technology-governance-regulation-and-capital"')) {
  html = html.replace(/\s*<h2 id="7-historical-significance-and-limitations">/, '\n' + governanceHtml + '        <h2 id="7-historical-significance-and-limitations">');
}
if (!html.includes('id="ref-18"')) {
  const refsHtml = `        <p><a id="ref-18"></a><strong>18.</strong> Biopure Corporation. SEC Form 10-K: biologic manufacturing requirements, GMP inspection history and executive roles. <a href="https://www.sec.gov/Archives/edgar/data/815508/000095013504000426/b49311bce10vk.htm">SEC filing</a>.</p>\n        <p><a id="ref-19"></a><strong>19.</strong> Feola M, Simoni J, Canizaro PC. Quality control of hemoglobin solutions: purity before modification. <em>Artificial Organs</em>. 1991. <a href="https://pubmed.ncbi.nlm.nih.gov/1867535/">PubMed</a>.</p>\n        <p><a id="ref-20"></a><strong>20.</strong> Production of modified crosslinked cell-free hemoglobin for human use: quantitative determination of endotoxin contamination. <a href="https://pubmed.ncbi.nlm.nih.gov/8259598/">PubMed</a>.</p>\n        <p><a id="ref-21"></a><strong>21.</strong> European Medicines Agency. Oxyglobin regulatory history and pre-authorisation manufacturing inspection. <a href="https://www.ema.europa.eu/en/documents/procedural-steps/oxyglobin-epar-procedural-steps-taken-authorisation_en.pdf">EMA</a>.</p>\n        <p><a id="ref-22"></a><strong>22.</strong> U.S. Securities and Exchange Commission. J.P. Morgan Securities Inc.; Biopure described as a "cold" IPO. <a href="https://www.sec.gov/enforcement-litigation/litigation-releases/lr-18385">SEC Litigation Release No. 18385</a>.</p>\n        <p><a id="ref-23"></a><strong>23.</strong> SEC-filed successor-company prospectus discussing Biopure's later market capitalization and product history. <a href="https://www.sec.gov/Archives/edgar/data/1615647/000149315222011184/forms-1.htm">SEC filing</a>.</p>\n        <p><a id="ref-24"></a><strong>24.</strong> U.S. Securities and Exchange Commission. SEC Charges Biopure and Executives. 14 Sep 2005. <a href="https://www.sec.gov/enforcement-litigation/litigation-releases/lr-19376">SEC Litigation Release No. 19376</a>.</p>\n        <p><a id="ref-25"></a><strong>25.</strong> U.S. Securities and Exchange Commission. SEC settlement with Biopure Corporation. 12 Sep 2006. <a href="https://www.sec.gov/enforcement-litigation/litigation-releases/lr-19825">SEC Litigation Release No. 19825</a>.</p>\n        <p><a id="ref-26"></a><strong>26.</strong> Biopure Corporation. Form 8-K, 18 Aug 2009: bankruptcy auction and OPK Biotech asset purchase. <a href="https://www.sec.gov/Archives/edgar/data/815508/000119312509180106/d8k.htm">SEC filing</a>.</p>\n`;
  html = html.replace(/\s*<h2 id="copyright-and-permissions">/, '\n' + refsHtml + '        <h2 id="copyright-and-permissions">');
}
html = html.replaceAll('—','-').replaceAll('–','-');
fs.writeFileSync(htmlPath, html);
